
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hora.de.k8s.adawolfs.github.io
  resources:
  - speakers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hora.de.k8s.adawolfs.github.io
  resources:
  - speakers/status
  verbs:
  - get
  - patch
  - update
